on:
  push:
  pull_request:

jobs:
  changed_states:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"
      - id: filter
        run: |
          echo ::set-output name=filtered_files::"$(jq -rcM '[.[] | select(. | contains(".sls"))]' <<< '${{ steps.files.outputs.added_modified }}')"
    outputs:
      matrix: ${{ steps.filter.outputs.filtered_files }}

  test_states:
    needs: changed_states

    runs-on: ubuntu-latest

    strategy:
      matrix:
        state: ${{ fromJson(needs.changed_states.outputs.matrix) }}

    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: docker://teamdfir/sift-saltstack-tester:focal
          run: |
            mkdir -p /srv/salt  
            ln -s /github/workspace/sift /srv/salt/
            salt-call -l debug --local --retcode-passthrough --state-output=mixed state.sls ${{ matrix.state }} pillar="{sift_user: root}"
